/**
 * CareConnect Application Configuration
 * Defines system metadata, Phase flags, supported languages, and detailed 8-Phase roadmap structure.
 */

export interface PhaseInfo {
  number: number;
  name: string;
  purpose: string;
  status: 'COMPLETED' | 'IN_PROGRESS' | 'NOT STARTED';
  isCurrent: boolean;
  isLocked: boolean;
  features: string[];
  subFeatures?: string[];
}

export const APP_CONFIG = {
  name: 'CareConnect',
  tagline: 'AI-Powered Clinical History-Taking & Medical Document Digitization',
  version: '1.2.0-phase2',
  hospitalName: 'CareConnect Healthcare Platform',
  currentPhase: 2,
  
  supportedLanguages: [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
    { code: 'kn', name: 'Kannada', nativeName: 'கன்னડ' },
  ],

  phases: [
    {
      number: 1,
      name: 'PHASE 1 — FOUNDATION',
      purpose: 'Establish the technical and UI foundation of CareConnect.',
      status: 'COMPLETED',
      isCurrent: false,
      isLocked: false,
      features: [
        'Project architecture',
        'Application shell',
        'Routing',
        'Patient and Doctor role structure',
        'Database foundation',
        'Data models/types',
        'Global design system',
        'Responsive foundation',
        'Future service interfaces',
      ],
      subFeatures: [
        'Vite + React + TypeScript scaffolding',
        'Global CSS tokens & high contrast accessibility',
        '10 Core relational database entities (PostgreSQL & Prisma)',
        'Interface contracts for AI, STT, OCR, Summary, RedFlags, ABHA, HIS',
      ],
    },
    {
      number: 2,
      name: 'PHASE 2 — PATIENT ONBOARDING',
      purpose: 'Enable patient identification, language selection, registration, ABHA authentication, and clinical consent.',
      status: 'COMPLETED',
      isCurrent: true,
      isLocked: false,
      features: [
        'Welcome screen',
        'Language selection',
        'Patient registration/login',
        'ABHA/demo identification',
        'Consent',
        'Patient profile',
        'Department selection',
      ],
      subFeatures: [
        'Multilingual welcome portal',
        'ABHA health ID lookup stub',
        'Clinical data privacy consent form',
        'Department OPD queue assignment',
      ],
    },
    {
      number: 3,
      name: 'PHASE 3 — AI CLINICAL HISTORY',
      purpose: 'Interactive voice/touch conversational AI assistant for comprehensive medical history taking.',
      status: 'NOT STARTED',
      isCurrent: false,
      isLocked: true,
      features: [
        'Conversational AI',
        'Voice input',
        'Speech-to-text',
        'Touch/tap answers',
        'Adaptive questioning',
        'Chief complaint',
        'HPI',
        'Past medical history',
        'Past surgical history',
        'Drug history',
        'Allergy history',
        'Family history',
        'Personal history',
        'Review of systems',
        'Interview progress tracking',
      ],
      subFeatures: [
        'Voice STT recognition engine',
        'Adaptive question flow generator',
        'Multi-system review (ROS)',
        'Real-time interview completion tracker',
      ],
    },
    {
      number: 4,
      name: 'PHASE 4 — MEDICAL DOCUMENT AI',
      purpose: 'Intelligent OCR & medical entity extraction for prescriptions, lab reports, and discharge summaries.',
      status: 'NOT STARTED',
      isCurrent: false,
      isLocked: true,
      features: [
        'Upload documents',
        'Camera/scan',
        'OCR',
        'Handwritten prescription processing',
        'Printed document processing',
        'Diagnosis extraction',
        'Medicine extraction',
        'Dosage extraction',
        'Investigation/lab extraction',
        'Date extraction',
        'Document organization',
        'Medical timeline',
        'Abnormal-value highlighting',
      ],
      subFeatures: [
        'Kiosk camera scanner integration',
        'Handwritten medical text OCR',
        'Lab abnormal result auto-highlighter',
        'Chronological medical timeline mapper',
      ],
    },
    {
      number: 5,
      name: 'PHASE 5 — STRUCTURED CLINICAL SUMMARY',
      purpose: 'Synthesize patient interview and document OCR data into a physician-ready clinical summary.',
      status: 'NOT STARTED',
      isCurrent: false,
      isLocked: true,
      features: [
        'Combine patient interview and document data',
        'Generate structured clinical history',
        'Chief complaint',
        'HPI',
        'Past medical/surgical history',
        'Drug/allergy history',
        'Family history',
        'Personal history',
        'Review of systems',
        'Previous investigations',
        'Physician-ready summary',
        'Patient verification',
        'Editable summary',
      ],
      subFeatures: [
        'Standard medical summary format generator',
        'Patient review & edit verification screen',
        'Physician-ready structured output export',
      ],
    },
    {
      number: 6,
      name: 'PHASE 6 — DOCTOR PORTAL',
      purpose: 'Physician dashboard for reviewing patient queues, clinical summaries, timelines, and sign-offs.',
      status: 'NOT STARTED',
      isCurrent: false,
      isLocked: true,
      features: [
        'Doctor login',
        'Patient queue',
        'Priority patients',
        'Patient profile',
        'Clinical history',
        'Clinical summary',
        'Medical documents',
        'Medical timeline',
        'AI alerts',
        'Edit/confirm',
        'Doctor notes',
      ],
      subFeatures: [
        'OPD room patient triage queue',
        'Interactive summary review & editing',
        'Doctor sign-off & clinical notes append',
      ],
    },
    {
      number: 7,
      name: 'PHASE 7 — CLINICAL INTELLIGENCE + AYUSH',
      purpose: 'Detect clinical red flags, assign priority triage, and process specialized AYUSH history.',
      status: 'NOT STARTED',
      isCurrent: false,
      isLocked: true,
      features: [
        'Red-flag detection',
        'Priority triage alerts',
        'AYUSH workflow',
        'Dashavidha Pariksha',
        'Specialized AYUSH history',
        'Clinical warning states',
      ],
      subFeatures: [
        'Emergency triage alert triggers',
        'Ayurveda Dashavidha Pariksha assessment',
        'Clinical safety warning states',
      ],
    },
    {
      number: 8,
      name: 'PHASE 8 — INTEGRATION + FINAL POLISH',
      purpose: 'ABDM/HIS ecosystem integration, accessibility, multilingual expansion, and SIH demonstration flow.',
      status: 'NOT STARTED',
      isCurrent: false,
      isLocked: true,
      features: [
        'ABHA integration architecture',
        'ABDM integration architecture',
        'HIS/EMR integration',
        'Consent management',
        'Security/privacy',
        'Multilingual support',
        'Accessibility',
        'Demo data',
        'Error handling',
        'Responsive testing',
        'Final end-to-end testing',
      ],
      subFeatures: [
        'ABDM health data exchange hooks',
        'Hospital EMR push pipeline',
        'SIH 2026 live demonstration workflow',
      ],
    },
  ] as PhaseInfo[],

  accessibility: {
    minTouchTargetPx: 48,
    contrastRatioMin: 4.5,
    fontScaleOptions: ['normal', 'large', 'extra-large'],
  },
};
